name: jet_server
description: An HTTP server optimized for production servers.
version: 0.1.0
repository: https://github.com/wdestroier/jet_server

environment:
  sdk: ^3.10.0

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
